import {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	IHttpRequestOptions,
	IHttpRequestMethods,
	IDataObject,
	NodeApiError,
} from 'n8n-workflow';

// Try to import credential map (generated by script)
let findCredentialIdByNameFromMap: ((name: string) => string | null) | null = null;
try {
	// credentialMap is in dist/ but we're in dist/nodes/DynamicHttpWithCredentials/
	// Try relative path first (../../credentialMap)
	const credentialMap = require('../../credentialMap');
	findCredentialIdByNameFromMap = credentialMap.findCredentialIdByName;
} catch (e) {
	// Try alternative paths
	try {
		const credentialMap = require('./credentialMap');
		findCredentialIdByNameFromMap = credentialMap.findCredentialIdByName;
	} catch (e2) {
		try {
			const credentialMap = require('../credentialMap');
			findCredentialIdByNameFromMap = credentialMap.findCredentialIdByName;
		} catch (e3) {
			// Map not available, will skip this method
		}
	}
}

// ============================================================================
// Constants
// ============================================================================

const DEFAULT_TIMEOUT = 300000; // 5 minutes (300000ms) as per requirements
const MAX_TIMEOUT = 600000; // 10 minutes maximum for security
const DEFAULT_RETRY_ATTEMPTS = 3;
const DEFAULT_RETRY_BASE_DELAY_MS = 1000;
const VALID_HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];
const METHODS_WITH_BODY = ['POST', 'PUT', 'PATCH'];
const CREDENTIAL_CACHE_TTL = 2 * 60 * 1000; // 2 minutes
const NAME_TO_ID_CACHE_TTL = 5 * 60 * 1000; // 5 minutes
const DEFAULT_CREDENTIAL_TYPE = 'httpHeaderAuth';
const DEFAULT_HEADER_NAME = 'Authorization';
const BEARER_PREFIX = 'Bearer ';
const DEFAULT_HEADERS = {
	'Content-Type': 'application/json; charset=utf-8',
	'Accept-Encoding': 'gzip',
	'Accept': 'application/json; charset=utf-8',
};
const DEFAULT_COMPANY_NAME = 'N/A';

// Security limits
const MAX_BODY_SIZE = 10 * 1024 * 1024; // 10MB maximum body size
const MAX_CREDENTIAL_NAME_LENGTH = 255; // Maximum credential name length
const MIN_CREDENTIAL_NAME_LENGTH = 1; // Minimum credential name length
const CREDENTIAL_NAME_PATTERN = /^[a-zA-Z0-9_-]+$/; // Alphanumeric, underscore, hyphen only

// ============================================================================
// Security Functions
// ============================================================================

/**
 * Validates that a URL is safe to use (prevents SSRF attacks)
 * Blocks:
 * - localhost and variants
 * - Private IP ranges (RFC 1918)
 * - Cloud metadata endpoints
 * - Non-HTTP/HTTPS protocols
 * 
 * @param url - The URL to validate
 * @returns true if the URL is safe, false otherwise
 */
function isValidUrl(url: string): boolean {
	try {
		const parsed = new URL(url);
		const hostname = parsed.hostname.toLowerCase();
		
		// 1. Only allow HTTP and HTTPS protocols
		if (!['http:', 'https:'].includes(parsed.protocol)) {
			return false;
		}
		
		// 2. Block localhost and variants
		const blockedHosts = [
			'localhost',
			'127.0.0.1',
			'0.0.0.0',
			'::1',
			'[::1]'
		];
		if (blockedHosts.includes(hostname)) {
			return false;
		}
		
		// 3. Block private IP ranges (RFC 1918)
		// 10.0.0.0/8
		if (/^10\./.test(hostname)) {
			return false;
		}
		// 172.16.0.0/12
		if (/^172\.(1[6-9]|2[0-9]|3[01])\./.test(hostname)) {
			return false;
		}
		// 192.168.0.0/16
		if (/^192\.168\./.test(hostname)) {
			return false;
		}
		
		// 4. Block cloud metadata endpoints
		// AWS, GCP, Azure: 169.254.169.254
		if (/^169\.254\.169\.254/.test(hostname)) {
			return false;
		}
		
		// 5. Block link-local addresses (169.254.0.0/16)
		if (/^169\.254\./.test(hostname)) {
			return false;
		}
		
		// 6. Block multicast addresses (224.0.0.0/4)
		if (/^22[4-9]\.|^23[0-9]\./.test(hostname)) {
			return false;
		}
		
		return true;
	} catch {
		// Invalid URL format
		return false;
	}
}

// ============================================================================
// Type Definitions
// ============================================================================

interface CredentialData {
	name?: string;
	value?: string;
	token?: string;
	[key: string]: unknown;
}

interface CachedCredential {
	credential: CredentialData;
	expiresAt: number;
}

interface CachedNameToId {
	id: string;
	expiresAt: number;
}

interface NodeOptions {
	timeout?: number;
	retry?: boolean;
	maxRetries?: number;
	retryDelay?: number;
	enableLogging?: boolean;
	continueOnFail?: boolean;
}

interface CredentialSearchResult {
	id: string;
	name?: string;
}

// ============================================================================
// Main Node Class
// ============================================================================

export class DynamicHttpWithCredentials implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'HTTP Request (Dynamic Credentials)',
		name: 'dynamicHttpWithCredentials',
		icon: 'file:icon.svg',
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["credentialName"] || "Dynamic"}}',
		description: 'Makes an HTTP request with dynamically selected credentials per item. Supports multiple credential types and HTTP methods.',
		defaults: {
			name: 'HTTP Request (Dynamic Credentials)',
		},
		inputs: ['main'],
		outputs: ['main'],
		credentials: [
			{
				name: 'httpHeaderAuth',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'Credential Name (Dynamic)',
				name: 'credentialName',
				type: 'string',
				default: '',
				required: true,
				description: 'Name of the credential to use. Use expression: ={{ $json.credentialName }}',
			},
			{
				displayName: 'Method',
				name: 'method',
				type: 'options',
				options: [
					{
						name: 'GET',
						value: 'GET',
					},
					{
						name: 'POST',
						value: 'POST',
					},
					{
						name: 'PUT',
						value: 'PUT',
					},
					{
						name: 'PATCH',
						value: 'PATCH',
					},
					{
						name: 'DELETE',
						value: 'DELETE',
					},
					{
						name: 'HEAD',
						value: 'HEAD',
					},
					{
						name: 'OPTIONS',
						value: 'OPTIONS',
					},
				],
				default: 'GET',
				description: 'The HTTP method to use',
			},
			{
				displayName: 'URL',
				name: 'url',
				type: 'string',
				default: '',
				required: true,
				description: 'The URL to make the request to. Use expression: ={{ $json.url }}',
			},
			{
				displayName: 'Send Body',
				name: 'sendBody',
				type: 'boolean',
				displayOptions: {
					show: {
						method: METHODS_WITH_BODY,
					},
				},
				default: false,
				description: 'Whether to send a body in the request',
			},
			{
				displayName: 'Body Content Type',
				name: 'bodyContentType',
				type: 'options',
				displayOptions: {
					show: {
						sendBody: [true],
						method: METHODS_WITH_BODY,
					},
				},
				options: [
					{
						name: 'JSON',
						value: 'json',
					},
					{
						name: 'Raw',
						value: 'raw',
					},
					{
						name: 'Form-Data',
						value: 'form-data',
					},
					{
						name: 'Form-Urlencoded',
						value: 'form-urlencoded',
					},
				],
				default: 'json',
				description: 'Content type for the body',
			},
			{
				displayName: 'Body',
				name: 'body',
				type: 'string',
				displayOptions: {
					show: {
						sendBody: [true],
						method: METHODS_WITH_BODY,
					},
				},
				default: '',
				description: 'The body to send. Use expression: ={{ $json.body }}',
			},
			{
				displayName: 'Options',
				name: 'options',
				type: 'collection',
				placeholder: 'Add Option',
				default: {},
				options: [
					{
						displayName: 'Timeout',
						name: 'timeout',
						type: 'number',
						typeOptions: {
							minValue: 1,
							maxValue: MAX_TIMEOUT,
						},
						default: DEFAULT_TIMEOUT,
						description: `Time in ms to wait for the remote server to respond (max: ${MAX_TIMEOUT / 1000 / 60} minutes)`,
					},
					{
						displayName: 'Retry',
						name: 'retry',
						type: 'boolean',
						default: false,
						description: 'Whether to retry on failure',
					},
					{
						displayName: 'Max Retries',
						name: 'maxRetries',
						type: 'number',
						typeOptions: {
							minValue: 1,
							maxValue: 10,
						},
						default: DEFAULT_RETRY_ATTEMPTS,
						displayOptions: {
							show: {
								retry: [true],
							},
						},
						description: 'Maximum number of retry attempts',
					},
					{
						displayName: 'Continue On Fail',
						name: 'continueOnFail',
						type: 'boolean',
						default: false,
						description: 'Whether to continue processing other items if one fails',
					},
					{
						displayName: 'Enable Logging',
						name: 'enableLogging',
						type: 'boolean',
						default: false,
						description: 'Whether to enable debug logging (credentials are never logged)',
					},
				],
			},
		],
	};

	// Static cache for credentials during execution (with TTL) - shared across instances
	protected static credentialCache: Map<string, CachedCredential> = new Map();
	
	// Static cache for credential name to ID mappings (with TTL) - avoids repeated searches
	protected static nameToIdCache: Map<string, CachedNameToId> = new Map();

	// ============================================================================
	// Helper Methods
	// ============================================================================

	/**
	 * Sanitizes log messages to mask sensitive credential information with asterisks
	 * OPTIMIZED: Pre-compiled regex patterns for better performance
	 */
	private static readonly CREDENTIAL_ID_REGEX = /\b([a-zA-Z0-9]{16,20})\b/g;
	private static readonly BEARER_TOKEN_REGEX = /Bearer\s+([A-Za-z0-9_-]{15,})/gi;
	private static readonly LONG_TOKEN_REGEX = /\b([A-Za-z0-9_-]{25,})\b/g;
	// Pattern to detect URLs (generic, no hardcoded domains)
	private static readonly URL_PATTERNS = /(http:\/\/|https:\/\/|:\/\/|\.com|\.org|\.net|\.io|\.ca|\.co|api\/v|\/api\/|\/v\d+\/)/i;
	// Additional patterns for sensitive data
	private static readonly API_KEY_REGEX = /(api[_-]?key|apikey)\s*[:=]\s*([A-Za-z0-9_-]{20,})/gi;
	private static readonly SECRET_REGEX = /(secret|password|token|key)\s*[:=]\s*([A-Za-z0-9_-]{15,})/gi;
	private static readonly COMMON_WORDS_SET = new Set([
		'credentialshelper', 'getdecrypted', 'authorization', 'header', 'length', 'bearer',
		'content-type', 'accept-encoding', 'accept', 'processing', 'found', 'clearing',
		'set', 'waiting', 'fetching', 'calling', 'successfully', 'retrieved', 'credential',
		'making', 'http', 'request', 'attempt', 'successful', 'cache', 'miss', 'expired',
		'original', 'node', 'id', 'for', 'to', 'with', 'exists', 'keys', 'structure',
		'data', 'added', 'final', 'get', 'post', 'put', 'patch', 'delete'
	]);

	private sanitizeLogMessage(message: string): string {
		// Replace API keys
		message = message.replace(DynamicHttpWithCredentials.API_KEY_REGEX, (_match, keyName, keyValue) => {
			return `${keyName}: ${keyValue.substring(0, 4)}******${keyValue.substring(keyValue.length - 4)}`;
		});
		
		// Replace secrets/passwords/tokens
		message = message.replace(DynamicHttpWithCredentials.SECRET_REGEX, (_match, secretName, secretValue) => {
			return `${secretName}: ******`;
		});
		
		// Replace credential IDs (16-20 character alphanumeric strings)
		message = message.replace(DynamicHttpWithCredentials.CREDENTIAL_ID_REGEX, (match, _fullMatch, offset) => {
			const before = message.substring(Math.max(0, offset - 20), offset);
			const after = message.substring(offset + match.length, Math.min(message.length, offset + match.length + 20));
			const context = (before + match + after).toLowerCase();
			
			// Check if it's part of a common word
			for (const word of DynamicHttpWithCredentials.COMMON_WORDS_SET) {
				if (context.includes(word)) {
					return match;
				}
			}
			
			// Mask credential ID
			return match.length >= 6 
				? match.substring(0, 2) + '******' + match.substring(match.length - 2)
				: '******';
		});
		
		// Replace Bearer tokens
		message = message.replace(DynamicHttpWithCredentials.BEARER_TOKEN_REGEX, (_match, token) => {
			return 'Bearer ' + token.substring(0, 4) + '******' + token.substring(token.length - 4);
		});
		
		// Replace long tokens (avoiding URLs)
		message = message.replace(DynamicHttpWithCredentials.LONG_TOKEN_REGEX, (match, _fullMatch, offset) => {
			const before = message.substring(Math.max(0, offset - 10), offset);
			const after = message.substring(offset + match.length, Math.min(message.length, offset + match.length + 10));
			const context = (before + match + after).toLowerCase();
			
			// Don't mask URLs
			if (DynamicHttpWithCredentials.URL_PATTERNS.test(context)) {
				return match;
			}
			
			return match.substring(0, 4) + '******' + match.substring(match.length - 4);
		});
		
		return message;
	}

	/**
	 * Logs a message if logging is enabled, sanitizing sensitive information
	 */
	private log(options: NodeOptions | undefined, message: string, data?: unknown): void {
		if (options?.enableLogging) {
			const timestamp = new Date().toISOString();
			const sanitizedMessage = this.sanitizeLogMessage(message);
			if (data) {
				const sanitizedData = this.sanitizeData(data);
				console.log(`[${timestamp}] [DynamicHttpWithCredentials] ${sanitizedMessage}`, sanitizedData);
			} else {
				console.log(`[${timestamp}] [DynamicHttpWithCredentials] ${sanitizedMessage}`);
			}
		}
	}

	/**
	 * Sanitizes data objects to hide sensitive information
	 */
	private sanitizeData(data: unknown): unknown {
		if (!data || typeof data !== 'object') {
			return data;
		}
		
		if (Array.isArray(data)) {
			return data.map(item => this.sanitizeData(item));
		}
		
		const sanitized: Record<string, unknown> = {};
		const sensitiveKeys = new Set([
			'value', 'token', 'password', 'secret', 'key', 'credential', 'authorization', 'bearer',
			'apikey', 'api_key', 'api-key', 'access_token', 'access-token', 'refresh_token', 'refresh-token',
			'private_key', 'private-key', 'privatekey', 'public_key', 'public-key', 'publickey',
			'passphrase', 'pass-phrase', 'passphrase', 'session', 'sessionid', 'session_id',
			'cookie', 'cookies', 'auth', 'authentication', 'jwt', 'oauth'
		]);
		
		for (const key in data) {
			const lowerKey = key.toLowerCase();
			const isSensitive = Array.from(sensitiveKeys).some(sk => lowerKey.includes(sk));
			const value = (data as Record<string, unknown>)[key];
			
			if (isSensitive) {
				if (typeof value === 'string' && value.length > 0) {
					// Mask strings of any length (not just > 10)
					if (value.length <= 4) {
						sanitized[key] = '****';
					} else {
						sanitized[key] = value.substring(0, 2) + '******' + value.substring(value.length - 2);
					}
				} else if (typeof value === 'object' && value !== null) {
					// Recursively sanitize nested objects
					sanitized[key] = this.sanitizeData(value);
				} else {
					sanitized[key] = '***';
				}
			} else if (typeof value === 'object' && value !== null) {
				sanitized[key] = this.sanitizeData(value);
			} else {
				sanitized[key] = value;
			}
		}
		
		return sanitized;
	}

	/**
	 * Retrieves the credentialStore object from the executeFunctions context.
	 * Based on TrkDynamicHttp implementation which works correctly.
	 */
	protected static getCredentialStore(executeFunctions: IExecuteFunctions): unknown {
		try {
			const workflow = (executeFunctions as { getWorkflow?: () => unknown }).getWorkflow?.();
			if (!workflow) {
				return null;
			}
			
			// Try various ways to access credentialStore
			const workflowAny = workflow as { credentialStore?: unknown };
			const helpersAny = (executeFunctions as { helpers?: { credentialStore?: unknown } }).helpers;
			const getCredentialStoreFn = (executeFunctions as { getCredentialStore?: () => unknown }).getCredentialStore;
			
			return workflowAny.credentialStore || helpersAny?.credentialStore || getCredentialStoreFn?.() || null;
		} catch {
			// Silently fail - credentialStore is optional
			return null;
		}
	}

	/**
	 * Helper function to find credential in an array
	 */
	private static findCredentialInArray(
		creds: CredentialSearchResult[],
		normalizedSearch: string
	): CredentialSearchResult | null {
		// Try exact match first (fastest)
		let found = creds.find(cred => cred.id === normalizedSearch || cred.name === normalizedSearch);
		if (found?.id) {
			return found;
		}
		
		// Try case-insensitive match for name
		const lowerSearch = normalizedSearch.toLowerCase();
		found = creds.find(cred => cred.name?.toLowerCase() === lowerSearch);
		return found?.id ? found : null;
	}

	/**
	 * Fetches a credential from cache or from n8n's credential store.
	 * OPTIMIZED: Removed unnecessary delays, improved error handling
	 */
	protected async getCachedCredential(
		executeFunctions: IExecuteFunctions,
		credentialId: string,
		credentialType: string,
		options: NodeOptions | undefined,
		itemIndex?: number,
	): Promise<CredentialData | null> {
		const now = Date.now();
		const cached = DynamicHttpWithCredentials.credentialCache.get(credentialId);

		if (cached && cached.expiresAt > now) {
			this.log(options, `Using cached credential for ID: ${credentialId}`);
			return cached.credential;
		}

		// this.log(options, `Fetching credential for ID: ${credentialId} (cache miss or expired)`);
		let credentialData: CredentialData | null = null;

		try {
			// Method 1: Try additionalData.credentialsHelper.getDecrypted() FIRST (most direct)
			const additionalData = (executeFunctions as { getAdditionalData?: () => unknown }).getAdditionalData?.() 
				|| (executeFunctions as { additionalData?: unknown }).additionalData;
			
			if (additionalData && typeof additionalData === 'object') {
				const credentialsHelper = (additionalData as { credentialsHelper?: { getDecrypted?: unknown } }).credentialsHelper;
				if (credentialsHelper && typeof credentialsHelper.getDecrypted === 'function') {
					try {
						const node = (executeFunctions as { getNode?: () => unknown }).getNode?.();
						const workflow = (executeFunctions as { getWorkflow?: () => unknown }).getWorkflow?.();
						
						// Try to find credential name from workflow
						let credentialName = credentialId;
						if (workflow && typeof workflow === 'object') {
							const workflowCreds = (workflow as { credentials?: Record<string, unknown> }).credentials;
							if (workflowCreds) {
								for (const [type, creds] of Object.entries(workflowCreds)) {
									if (type === credentialType || type.includes(credentialType)) {
										if (Array.isArray(creds)) {
											const found = creds.find((cred: unknown) => 
												typeof cred === 'object' && cred !== null && 
												(cred as { id?: string }).id === credentialId
											);
											if (found && typeof found === 'object' && found !== null) {
												const name = (found as { name?: string }).name;
												if (name) {
													credentialName = name;
													break;
												}
											}
										}
									}
								}
							}
						}
						
						const nodeCredentials = { id: credentialId, name: credentialName };
						const workflowMode = (workflow && typeof workflow === 'object' 
							? (workflow as { mode?: string }).mode 
							: 'manual') || 'manual';
						
						const creds = await (credentialsHelper.getDecrypted as (
							additionalData: unknown,
							nodeCredentials: { id: string; name: string },
							credentialType: string,
							mode: string
						) => Promise<unknown>)(additionalData, nodeCredentials, credentialType, workflowMode);
						
						if (creds && typeof creds === 'object') {
							this.log(options, `✅ Credential retrieved successfully`);
							const credsAny = creds as Record<string, unknown>;
							const credValue = String(credsAny.value || credsAny.token || '');
							credentialData = {
								name: (credsAny.name as string) || DEFAULT_HEADER_NAME,
								value: credValue || (credsAny.token as string) || '',
								...credsAny
							} as CredentialData;
						}
					} catch (e) {
						const error = e as { message?: string };
						this.log(options, `❌ credentialsHelper.getDecrypted failed: ${error.message || 'Unknown error'}`);
					}
				}
			}
			
			// Method 2: Try to get from credentialStore
			if (!credentialData) {
				const credentialStore = DynamicHttpWithCredentials.getCredentialStore(executeFunctions);
				if (credentialStore && typeof credentialStore === 'object') {
					const storeGet = (credentialStore as { get?: unknown }).get;
					if (typeof storeGet === 'function') {
						try {
							this.log(options, `Trying credentialStore.get('${credentialType}', '${credentialId}')...`);
							credentialData = await (storeGet as (type: string, id: string) => Promise<CredentialData | null>)(
								credentialType, 
								credentialId
							);
							if (credentialData) {
								this.log(options, `✅ Successfully retrieved credential from credentialStore`);
							}
						} catch (e) {
							const error = e as { message?: string };
							this.log(options, `❌ credentialStore.get failed: ${error.message || 'Unknown error'}`);
						}
					}
				}
			}
			
			// Method 3: Fallback - Use getCredentials (with delays to allow n8n to update)
			if (!credentialData) {
				this.log(options, `Trying getCredentials with node credential ID...`);
				const node = (executeFunctions as { getNode?: () => unknown }).getNode?.();
				if (node && typeof node === 'object') {
					const nodeCreds = (node as { credentials?: Record<string, { id?: string }> }).credentials;
					if (nodeCreds) {
						const originalCredId = nodeCreds[credentialType]?.id;
						
						// Clear previous credential if different
						if (originalCredId !== credentialId) {
							// Clear from node.credentials
							if (nodeCreds[credentialType]) {
								const credObj = nodeCreds[credentialType] as { id?: string; name?: string; value?: string };
								delete credObj.id;
								delete credObj.name;
								delete credObj.value;
							}
							
							// Wait after clearing
							await new Promise(resolve => setTimeout(resolve, 50));
						}
						
						// Set the new credential ID
						if (!nodeCreds[credentialType]) {
							nodeCreds[credentialType] = {};
						}
						nodeCreds[credentialType].id = credentialId;
						
						// Also set in node.parameters if available
						const nodeParameters = (node as { parameters?: { credentials?: Record<string, { id?: string }> } }).parameters;
						if (nodeParameters) {
							if (!nodeParameters.credentials) {
								nodeParameters.credentials = {};
							}
							if (!nodeParameters.credentials[credentialType]) {
								nodeParameters.credentials[credentialType] = {};
							}
							nodeParameters.credentials[credentialType].id = credentialId;
						}
						
						// Wait for credential ID change to propagate (only if changed)
						if (originalCredId !== credentialId) {
							await new Promise(resolve => setTimeout(resolve, 200));
						}
						
						try {
							const creds = itemIndex !== undefined 
								? await executeFunctions.getCredentials(credentialType, itemIndex)
								: await executeFunctions.getCredentials(credentialType);
							
							if (creds) {
								const credsAny = creds as { id?: string; __id?: string };
								const retrievedId = credsAny.id || credsAny.__id;
								if (retrievedId === credentialId || !retrievedId) {
									this.log(options, `✅ Successfully retrieved credential via getCredentials`);
									credentialData = creds as CredentialData;
								}
							}
						} catch (e) {
							const error = e as { message?: string };
							this.log(options, `❌ getCredentials failed: ${error.message || 'Unknown error'}`);
						} finally {
							// Restore original credential ID
							if (originalCredId !== undefined) {
								nodeCreds[credentialType].id = originalCredId;
							} else {
								delete nodeCreds[credentialType].id;
							}
						}
					}
				}
			}

			if (credentialData) {
				DynamicHttpWithCredentials.credentialCache.set(credentialId, {
					credential: credentialData,
					expiresAt: now + CREDENTIAL_CACHE_TTL,
				});
				return credentialData;
			} else {
				this.log(options, `❌ All methods failed to retrieve credential data`);
			}
		} catch (error) {
			const err = error as { message?: string; stack?: string };
			this.log(options, `❌ Error fetching credential for ID ${credentialId}: ${err.message || 'Unknown error'}`);
			if (err.stack) {
				this.log(options, `Error stack: ${err.stack}`);
			}
			return null;
		}

		return null;
	}

	/**
	 * Clears expired entries from cache (optimized: only expired, not all)
	 */
	protected static cleanExpiredCacheEntries(): void {
		const now = Date.now();
		
		// Clean credential cache
		for (const [key, cached] of DynamicHttpWithCredentials.credentialCache.entries()) {
			if (cached.expiresAt <= now) {
				DynamicHttpWithCredentials.credentialCache.delete(key);
			}
		}
		
		// Clean name-to-ID cache
		for (const [key, cached] of DynamicHttpWithCredentials.nameToIdCache.entries()) {
			if (cached.expiresAt <= now) {
				DynamicHttpWithCredentials.nameToIdCache.delete(key);
			}
		}
	}

	/**
	 * Checks if a string looks like an n8n credential ID
	 * OPTIMIZED: Fast validation for credential IDs
	 * n8n credential IDs are alphanumeric strings of 16-20 characters
	 * Examples: AbCdEfGhIjKlMnOp (16), XyZaBcDeFgHiJkLm (16)
	 */
	protected static isLikelyCredentialId(value: string): boolean {
		if (!value || typeof value !== 'string') {
			return false;
		}
		const trimmed = value.trim();
		const len = trimmed.length;
		// Fast path: Check length first (cheapest check)
		if (len < 16 || len > 20) {
			return false;
		}
		// Then check if it's alphanumeric (n8n IDs are always alphanumeric)
		return /^[a-zA-Z0-9]+$/.test(trimmed);
	}


	/**
	 * Sets the node's credential ID temporarily
	 */
	protected setNodeCredentialId(
		executeFunctions: IExecuteFunctions,
		credentialId: string,
		credentialType: string = DEFAULT_CREDENTIAL_TYPE
	): string | undefined {
		const node = (executeFunctions as any).getNode?.();
		if (!node || !node.credentials) {
			return undefined;
		}

		const originalCredId = node.credentials[credentialType]?.id;

		if (!node.credentials[credentialType]) {
			node.credentials[credentialType] = {};
		}
		node.credentials[credentialType].id = credentialId;

		return originalCredId;
	}

	/**
	 * Restores the original credential ID
	 */
	protected restoreNodeCredentialId(
		executeFunctions: IExecuteFunctions,
		originalCredId: string | undefined,
		credentialType: string = DEFAULT_CREDENTIAL_TYPE
	): void {
		const node = (executeFunctions as any).getNode?.();
		if (!node || !node.credentials || !node.credentials[credentialType]) {
			return;
		}

		if (originalCredId) {
			node.credentials[credentialType].id = originalCredId;
		} else {
			delete node.credentials[credentialType].id;
		}
	}

	/**
	 * Finds credential ID by name or ID
	 * OPTIMIZED: Uses credentialMap first, then cache, then searches
	 * Supports both credential name and credential ID
	 */
	protected async findCredentialIdByName(
		executeFunctions: IExecuteFunctions,
		credentialNameOrId: string,
		credentialType: string = DEFAULT_CREDENTIAL_TYPE,
		options?: NodeOptions
	): Promise<string | null> {
		if (!credentialNameOrId || credentialNameOrId.trim() === '') {
			return null;
		}

		const normalizedSearch = credentialNameOrId.trim();

		// OPTIMIZED PATH 1: Fast check for credential ID (most common case)
		if (DynamicHttpWithCredentials.isLikelyCredentialId(normalizedSearch)) {
			return normalizedSearch;
		}

		// OPTIMIZED PATH 2: Try credentialMap first (fastest lookup for names)
		if (findCredentialIdByNameFromMap) {
			const mapResult = findCredentialIdByNameFromMap(normalizedSearch);
			if (mapResult) {
				this.log(options, `✅ Found credential ID in map: '${normalizedSearch}' -> '${mapResult}'`);
				return mapResult;
			}
		}

		// OPTIMIZED PATH 3: Check cache (avoid repeated searches)
		const cacheKey = `${credentialType}:${normalizedSearch.toLowerCase()}`;
		const now = Date.now();
		const cached = DynamicHttpWithCredentials.nameToIdCache.get(cacheKey);
		if (cached && cached.expiresAt > now) {
			this.log(options, `✅ Found credential ID in cache: '${normalizedSearch}' -> '${cached.id}'`);
			return cached.id;
		}

		// Name search - try multiple methods (refactored to reduce duplication)
		let foundId: string | null = null;

		try {
			// OPTIMIZATION: Cache workflow and credentialStore (accessed multiple times)
			const workflow = (executeFunctions as { getWorkflow?: () => unknown }).getWorkflow?.();
			const credentialStore = workflow ? DynamicHttpWithCredentials.getCredentialStore(executeFunctions) : null;
			
			// Helper function to search in credential arrays/objects
			const searchInCreds = (creds: unknown): string | null => {
				if (Array.isArray(creds)) {
					const found = DynamicHttpWithCredentials.findCredentialInArray(
						creds as CredentialSearchResult[],
						normalizedSearch
					);
					return found?.id || null;
				} else if (creds && typeof creds === 'object') {
					const cred = creds as CredentialSearchResult;
					if (cred.id === normalizedSearch ||
						cred.name === normalizedSearch ||
						(cred.name && cred.name.toLowerCase() === normalizedSearch.toLowerCase())) {
						return cred.id || null;
					}
				}
				return null;
			};

			// Method 1: Try workflow credentials (most reliable)
			if (workflow && typeof workflow === 'object') {
				const workflowCreds = (workflow as { credentials?: Record<string, unknown> }).credentials;
				if (workflowCreds) {
					for (const [type, creds] of Object.entries(workflowCreds)) {
						if (type === credentialType || type.includes(credentialType)) {
							foundId = searchInCreds(creds);
							if (foundId) break;
						}
					}
				}

				// Try workflow.credentialsByType
				if (!foundId) {
					const credentialsByType = (workflow as { credentialsByType?: Record<string, unknown> }).credentialsByType;
					if (credentialsByType) {
						foundId = searchInCreds(credentialsByType[credentialType]);
					}
				}
			}

			// Method 2: Access through credentialStore (using cached value)
			if (!foundId && credentialStore && typeof credentialStore === 'object') {
				const storeGetAll = (credentialStore as { getAll?: unknown }).getAll;
				if (typeof storeGetAll === 'function') {
					try {
						const allCreds = await (storeGetAll as (type: string) => Promise<unknown>)(credentialType);
						foundId = searchInCreds(allCreds);
					} catch {
						// Silently continue
					}
				}
			}

			// Method 3: Access through helpers
			if (!foundId) {
				const helpers = (executeFunctions as { helpers?: unknown }).helpers;
				if (helpers && typeof helpers === 'object') {
					const getAllCreds = (helpers as { getAllCredentials?: unknown }).getAllCredentials;
					if (typeof getAllCreds === 'function') {
						try {
							const allCreds = await (getAllCreds as (type: string) => Promise<unknown>)(credentialType);
							foundId = searchInCreds(allCreds);
						} catch {
							// Silently continue
						}
					}

					const getCredsByType = (helpers as { getCredentialsByType?: unknown }).getCredentialsByType;
					if (!foundId && typeof getCredsByType === 'function') {
						try {
							const creds = await (getCredsByType as (type: string) => Promise<unknown>)(credentialType);
							foundId = searchInCreds(creds);
						} catch {
							// Silently continue
						}
					}
				}
			}

			// Method 4: Try node context
			if (!foundId) {
				const node = (executeFunctions as { getNode?: () => unknown }).getNode?.();
				if (node && typeof node === 'object') {
					const nodeCreds = (node as { credentials?: Record<string, CredentialSearchResult> }).credentials;
					if (nodeCreds?.[credentialType]) {
						const cred = nodeCreds[credentialType];
						if (cred.id === normalizedSearch ||
							cred.name === normalizedSearch ||
							(cred.name && cred.name.toLowerCase() === normalizedSearch.toLowerCase())) {
							foundId = cred.id || null;
						}
					}
				}
			}

			// Method 5: Try using credentialsHelper repositories (restored from original)
			if (!foundId) {
				const additionalData = (executeFunctions as { getAdditionalData?: () => unknown }).getAdditionalData?.() 
					|| (executeFunctions as { additionalData?: unknown }).additionalData;
				if (additionalData && typeof additionalData === 'object') {
					const credentialsHelper = (additionalData as { credentialsHelper?: { credentialsRepository?: unknown; sharedCredentialsRepository?: unknown } }).credentialsHelper;
					if (credentialsHelper) {
						// Try credentialsRepository first (user credentials)
						if (credentialsHelper.credentialsRepository && typeof credentialsHelper.credentialsRepository === 'object') {
							const repo = credentialsHelper.credentialsRepository as { find?: unknown; getAll?: unknown };
							// Try find method
							if (typeof repo.find === 'function') {
								try {
									const allCreds = await (repo.find as (query: { where: { type: string } }) => Promise<unknown>)({ where: { type: credentialType } });
									foundId = searchInCreds(allCreds);
								} catch {
									// Silently continue
								}
							}
							// Try getAll method
							if (!foundId && typeof repo.getAll === 'function') {
								try {
									const allCreds = await (repo.getAll as () => Promise<unknown>)();
									if (Array.isArray(allCreds)) {
										const filteredCreds = allCreds.filter((c: unknown) => 
											typeof c === 'object' && c !== null && (c as { type?: string }).type === credentialType
										);
										foundId = searchInCreds(filteredCreds);
									}
								} catch {
									// Silently continue
								}
							}
						}
						// Try sharedCredentialsRepository if credentialsRepository didn't work
						if (!foundId && credentialsHelper.sharedCredentialsRepository && typeof credentialsHelper.sharedCredentialsRepository === 'object') {
							const repo = credentialsHelper.sharedCredentialsRepository as { find?: unknown };
							if (typeof repo.find === 'function') {
								try {
									const allCreds = await (repo.find as (query: { where: { type: string } }) => Promise<unknown>)({ where: { type: credentialType } });
									foundId = searchInCreds(allCreds);
								} catch {
									// Silently continue
								}
							}
						}
					}
				}
			}

			// Method 6: Try using credential manager (restored from original)
			if (!foundId) {
				try {
					const node = (executeFunctions as { getNode?: () => unknown }).getNode?.();
					if (node) {
						const workflow = (executeFunctions as { getWorkflow?: () => unknown }).getWorkflow?.();
						if (workflow && typeof workflow === 'object') {
							const credentialManager = (workflow as { __credentialManager?: unknown; credentialManager?: unknown; __internal?: { credentialManager?: unknown } }).__credentialManager 
								|| (workflow as { credentialManager?: unknown }).credentialManager
								|| ((workflow as { __internal?: { credentialManager?: unknown } }).__internal?.credentialManager);
							if (credentialManager && typeof credentialManager === 'object') {
								const getAllCreds = (credentialManager as { getAllCredentials?: unknown }).getAllCredentials;
								if (typeof getAllCreds === 'function') {
									try {
										const allCreds = await (getAllCreds as (type: string) => Promise<unknown>)(credentialType);
										foundId = searchInCreds(allCreds);
									} catch {
										// Silently continue
									}
								}
							}
						}
					}
				} catch {
					// Silently continue
				}
			}

			// Cache the result if found
			if (foundId) {
				this.log(options, `✅ Found credential '${normalizedSearch}' -> '${foundId}'`);
				DynamicHttpWithCredentials.nameToIdCache.set(cacheKey, {
					id: foundId,
					expiresAt: now + NAME_TO_ID_CACHE_TTL,
				});
				return foundId;
			}

			this.log(options, `❌ Credential '${normalizedSearch}' not found after all search methods`);
			return null;
		} catch (error) {
			const err = error as { message?: string };
			this.log(options, `Error searching for credential: ${err.message || 'Unknown error'}`);
			return null;
		}
	}

	/**
	 * Calculates exponential backoff delay with jitter
	 */
	private static calculateRetryDelay(attempt: number, baseDelay: number): number {
		// Exponential backoff: baseDelay * 2^attempt
		const exponentialDelay = baseDelay * Math.pow(2, attempt);
		// Add jitter (random 0-25% of delay) to prevent thundering herd
		const jitter = Math.random() * exponentialDelay * 0.25;
		return Math.min(exponentialDelay + jitter, 30000); // Cap at 30 seconds
	}

	// ============================================================================
	// Main Execute Method
	// ============================================================================

	/**
	 * Gets parameter value, trying node parameter first, then item data
	 */
	private static getParameterOrItemData(executeFunctions: IExecuteFunctions, parameterName: string, itemIndex: number, itemData: Record<string, unknown>, defaultValue?: string): string {
		let value = executeFunctions.getNodeParameter(parameterName, itemIndex, defaultValue || '') as string;
		if (!value && itemData[parameterName]) {
			value = String(itemData[parameterName]).trim();
		}
		return value;
	}

	/**
	 * Transforms response data to include company name as key
	 * OPTIMIZED: Reduced allocations and early returns
	 */
	private static transformResponseData(responseData: unknown, company: string): Record<string, unknown> {
		if (!responseData) {
			return { [company]: null };
		}

		if (Array.isArray(responseData)) {
			return { [company]: responseData };
		}

		if (typeof responseData === 'object' && responseData !== null) {
			const responseObj = responseData as Record<string, unknown>;
			const keys = Object.keys(responseObj);
			
			// Fast path: if only one numeric key, return its value directly
			if (keys.length === 1 && /^\d+$/.test(keys[0])) {
				return { [company]: responseObj[keys[0]] };
			}
			
			// Check if all keys are numeric (optimized: early exit)
			if (keys.length > 0) {
				let allNumeric = true;
				for (let i = 0; i < keys.length; i++) {
					if (!/^\d+$/.test(keys[i])) {
						allNumeric = false;
						break;
					}
				}
				if (allNumeric && keys.length > 0) {
					return { [company]: responseObj[keys[0]] };
				}
			}
			
			return { [company]: responseData };
		}

		return { [company]: responseData };
	}

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		// Clean only expired cache entries (optimized: don't clear everything)
		DynamicHttpWithCredentials.cleanExpiredCacheEntries();
		
		const items = this.getInputData();
		const returnData: INodeExecutionData[] = [];
		// Create instance to access private methods
		const nodeInstance = new DynamicHttpWithCredentials();

		// OPTIMIZATION: Pre-extract and validate common parameters once
		const defaultMethod = this.getNodeParameter('method', 0, 'GET') as string;
		const defaultSendBody = this.getNodeParameter('sendBody', 0, false) as boolean;
		const defaultBodyContentType = this.getNodeParameter('bodyContentType', 0, 'json') as string;
		const defaultOptions = this.getNodeParameter('options', 0, {}) as NodeOptions;
		
		// OPTIMIZATION: Cache node object (accessed multiple times)
		const node = this.getNode();
		const nodeCreds = (node && typeof node === 'object') 
			? (node as { credentials?: Record<string, { id?: string }> }).credentials 
			: undefined;

		// OPTIMIZATION: Pre-load unique credentials to avoid repeated lookups
		const uniqueCredentialNames = new Set<string>();
		for (let i = 0; i < items.length; i++) {
			const credentialName = DynamicHttpWithCredentials.getParameterOrItemData(
				this, 'credentialName', i, items[i].json
			);
			if (credentialName && credentialName.trim()) {
				uniqueCredentialNames.add(credentialName.trim());
			}
		}

		// Pre-load credential IDs for unique credential names
		const credentialIdMap = new Map<string, string | null>();
		for (const credName of uniqueCredentialNames) {
			if (!DynamicHttpWithCredentials.isLikelyCredentialId(credName)) {
				const credId = await nodeInstance.findCredentialIdByName(this, credName, DEFAULT_CREDENTIAL_TYPE, defaultOptions);
				credentialIdMap.set(credName, credId);
			} else {
				credentialIdMap.set(credName, credName);
			}
		}

		for (let i = 0; i < items.length; i++) {
			let originalCredId: string | undefined;
			try {
				// Get parameters (use defaults if not item-specific)
				const method = this.getNodeParameter('method', i, defaultMethod) as string;
				const sendBody = this.getNodeParameter('sendBody', i, defaultSendBody) as boolean;
				const bodyContentType = this.getNodeParameter('bodyContentType', i, defaultBodyContentType) as string;
				const body = this.getNodeParameter('body', i, '') as string;
				const options = this.getNodeParameter('options', i, defaultOptions) as NodeOptions;
				
				// Get parameters from node or item data
				const url = DynamicHttpWithCredentials.getParameterOrItemData(this, 'url', i, items[i].json);
				const credentialName = DynamicHttpWithCredentials.getParameterOrItemData(this, 'credentialName', i, items[i].json);

				// OPTIMIZATION: Early validation before expensive operations
				if (!credentialName || credentialName.trim() === '') {
					throw new Error(`[Item ${i + 1}] credentialName is required. Provide it in node config or item data (e.g., {{ $json.credentialName }}).`);
				}

				// Security: Validate credential name format and length
				const trimmedCredentialName = credentialName.trim();
				if (trimmedCredentialName.length < MIN_CREDENTIAL_NAME_LENGTH || trimmedCredentialName.length > MAX_CREDENTIAL_NAME_LENGTH) {
					throw new Error(`[Item ${i + 1}] credentialName must be between ${MIN_CREDENTIAL_NAME_LENGTH} and ${MAX_CREDENTIAL_NAME_LENGTH} characters.`);
				}
				if (!CREDENTIAL_NAME_PATTERN.test(trimmedCredentialName)) {
					throw new Error(`[Item ${i + 1}] credentialName contains invalid characters. Only alphanumeric characters, underscores, and hyphens are allowed.`);
				}

				if (!url || url.trim() === '') {
					throw new Error(`[Item ${i + 1}] URL is required. Provide it in node config or item data (e.g., {{ $json.url }}).`);
				}

				// Security: Validate URL to prevent SSRF attacks
				const trimmedUrl = url.trim();
				if (!isValidUrl(trimmedUrl)) {
					throw new Error(`[Item ${i + 1}] URL is not allowed for security reasons. Only public HTTP/HTTPS URLs are permitted. Private IPs, localhost, and cloud metadata endpoints are blocked.`);
				}

				if (!VALID_HTTP_METHODS.includes(method)) {
					throw new Error(`[Item ${i + 1}] Invalid HTTP method: ${method}`);
				}

				// OPTIMIZATION: Use pre-loaded credential ID if available
				const normalizedCredName = credentialName.trim();
				let credentialId = credentialIdMap.get(normalizedCredName);
				
				// If not pre-loaded (shouldn't happen, but fallback for safety)
				if (credentialId === undefined) {
					credentialId = await nodeInstance.findCredentialIdByName(this, normalizedCredName, DEFAULT_CREDENTIAL_TYPE, options);
					credentialIdMap.set(normalizedCredName, credentialId);
				}
				
				if (!credentialId) {
					throw new Error(`[Item ${i + 1}] Credential with name or ID '${credentialName}' not found. Please ensure the credential exists in n8n and the name/ID matches exactly (case-sensitive for ID, case-insensitive for name).`);
				}

				// Set the credential ID (with delays to allow n8n to update internal state)
				// OPTIMIZATION: Only apply delays if credential actually changed
				if (nodeCreds) {
					if (!nodeCreds[DEFAULT_CREDENTIAL_TYPE]) {
						nodeCreds[DEFAULT_CREDENTIAL_TYPE] = {};
					}
					originalCredId = nodeCreds[DEFAULT_CREDENTIAL_TYPE].id;
					
					// Only clear and wait if credential is actually changing
					if (originalCredId !== credentialId) {
						// Clear previous credential to ensure n8n updates
						const credObj = nodeCreds[DEFAULT_CREDENTIAL_TYPE] as { id?: string; name?: string; value?: string };
						delete credObj.id;
						delete credObj.name;
						delete credObj.value;
						
						// Also clear from node.parameters if it exists
						const nodeParameters = (node as { parameters?: { credentials?: Record<string, { id?: string }> } }).parameters;
						if (nodeParameters?.credentials?.[DEFAULT_CREDENTIAL_TYPE]) {
							delete nodeParameters.credentials[DEFAULT_CREDENTIAL_TYPE].id;
						}
						
						// Wait after clearing to allow n8n to process the change
						await new Promise(resolve => setTimeout(resolve, 50));
						
						// Set the new credential ID
						nodeCreds[DEFAULT_CREDENTIAL_TYPE].id = credentialId;
						
						// Also set in node.parameters if available
						if (nodeParameters) {
							if (!nodeParameters.credentials) {
								nodeParameters.credentials = {};
							}
							if (!nodeParameters.credentials[DEFAULT_CREDENTIAL_TYPE]) {
								nodeParameters.credentials[DEFAULT_CREDENTIAL_TYPE] = {};
							}
							nodeParameters.credentials[DEFAULT_CREDENTIAL_TYPE].id = credentialId;
						}
						
						// Wait for credential ID change to propagate in n8n's internal state
						await new Promise(resolve => setTimeout(resolve, 150));
					} else {
						// Same credential - no delay needed, just ensure it's set
						nodeCreds[DEFAULT_CREDENTIAL_TYPE].id = credentialId;
					}
				}

				// Get the actual credential data (from cache or store)
				const creds = await nodeInstance.getCachedCredential(this, credentialId, DEFAULT_CREDENTIAL_TYPE, options, i);

				if (!creds || !creds.name || !creds.value) {
					throw new Error(`[Item ${i + 1}] Failed to retrieve full credential data for ID: ${credentialId}`);
				}

				// Credential data retrieved (details not logged for security)

				// OPTIMIZATION: Build headers more efficiently
				const headers: { [key: string]: string } = Object.assign({}, DEFAULT_HEADERS);
				
				// Add the credential header (optimized: single pass)
				const credValue = creds.value ? String(creds.value) : '';
				const credName = creds.name || DEFAULT_HEADER_NAME;
				
				if (!credValue) {
					throw new Error(`[Item ${i + 1}] Credential data is missing 'value' field. Structure: ${JSON.stringify(Object.keys(creds))}`);
				}
				
				// Build header value (add Bearer prefix if needed)
				let headerValue = credValue;
				if (credName === DEFAULT_HEADER_NAME && !headerValue.startsWith(BEARER_PREFIX)) {
					headerValue = `${BEARER_PREFIX}${headerValue}`;
				}
				
				headers[credName] = headerValue;
				
				// Security: Validate timeout (prevent excessive timeouts)
				const timeout = options.timeout || DEFAULT_TIMEOUT;
				if (timeout < 1 || timeout > MAX_TIMEOUT) {
					throw new Error(`[Item ${i + 1}] Timeout must be between 1 and ${MAX_TIMEOUT}ms (${MAX_TIMEOUT / 1000 / 60} minutes).`);
				}

				// Build request options
				const requestOptions: IHttpRequestOptions = {
					method: method as IHttpRequestMethods,
					headers: headers,
					url: url,
					json: true,
					timeout: timeout,
				};

				if (METHODS_WITH_BODY.includes(method) && sendBody) {
					// Security: Validate body size (prevent DoS attacks)
					if (body && body.length > MAX_BODY_SIZE) {
						throw new Error(`[Item ${i + 1}] Body size (${body.length} bytes) exceeds maximum allowed size of ${MAX_BODY_SIZE} bytes (${MAX_BODY_SIZE / 1024 / 1024}MB).`);
					}

					if (bodyContentType === 'json') {
						try {
							requestOptions.body = JSON.parse(body) as Record<string, unknown>;
						} catch (e) {
							const error = e as { message?: string };
							throw new Error(`[Item ${i + 1}] Invalid JSON body: ${error.message || 'Unknown error'}`);
						}
					} else if (bodyContentType === 'raw') {
						requestOptions.body = body;
					}
					// TODO: Implement form-data and form-urlencoded if needed
				}

				// Make request with exponential backoff retry
				let responseData: unknown;
				let attempts = 0;
				const maxRetries = options.retry ? (options.maxRetries || DEFAULT_RETRY_ATTEMPTS) : 0;
				const baseRetryDelay = options.retryDelay || DEFAULT_RETRY_BASE_DELAY_MS;

				while (attempts <= maxRetries) {
					try {
						nodeInstance.log(options, `Making HTTP request (Attempt ${attempts + 1}/${maxRetries + 1}): ${method} ${url}`);
						responseData = await this.helpers.request!(requestOptions);
						nodeInstance.log(options, `Request successful (Attempt ${attempts + 1})`);
						break; // Exit loop on success
					} catch (error) {
						const err = error as { message?: string };
						nodeInstance.log(options, `Request failed (Attempt ${attempts + 1}): ${err.message || 'Unknown error'}`);
						if (attempts < maxRetries) {
							const retryDelay = DynamicHttpWithCredentials.calculateRetryDelay(attempts, baseRetryDelay);
							nodeInstance.log(options, `Retrying in ${Math.round(retryDelay)}ms...`);
							await new Promise(resolve => setTimeout(resolve, retryDelay));
						} else {
							// Pass error directly to NodeApiError (as in original code)
							// eslint-disable-next-line @typescript-eslint/no-explicit-any
							const enhancedError = new NodeApiError(this.getNode(), error as any, {
								message: `[Item ${i + 1}] HTTP Request failed after ${maxRetries + 1} attempts: ${err.message || 'Unknown error'}`,
							});
							throw enhancedError;
						}
					}
					attempts++;
				}

				// Add metadata to the output with company at top level
				const company: string = String(items[i].json.company || DEFAULT_COMPANY_NAME);
				
				// OPTIMIZATION: Transform and build output in one pass
				const transformedResponse = DynamicHttpWithCredentials.transformResponseData(responseData, company);
				
				// Build output JSON (optimized: direct assignment)
				const outputJson: IDataObject = transformedResponse as IDataObject;
				outputJson._meta = {
					company: company,
					credentialName: credentialName,
					timestamp: new Date().toISOString(),
				} as IDataObject[string];
				
				// Preserve original input data for downstream processing (optional - uncomment if needed)
				//outputJson._originalInput = items[i].json as IDataObject[string];

				returnData.push({
					json: outputJson,
					pairedItem: { item: i },
				});

			} catch (error) {
				// Propagate error for the specific item
				const err = error as { message?: string };
				if (this.continueOnFail()) {
					const company = String(items[i].json.company || DEFAULT_COMPANY_NAME);
					returnData.push({ 
						json: { 
							company: company,
							error: err.message || 'Unknown error'
						}, 
						pairedItem: { item: i } 
					});
				} else {
					throw error;
				}
			} finally {
				// OPTIMIZATION: Use cached nodeCreds instead of re-fetching
				if (originalCredId !== undefined && nodeCreds?.[DEFAULT_CREDENTIAL_TYPE]) {
					nodeCreds[DEFAULT_CREDENTIAL_TYPE].id = originalCredId;
				}
			}
		}

		// Clean expired cache entries (optimized: only expired, not all)
		DynamicHttpWithCredentials.cleanExpiredCacheEntries();

		return [returnData];
	}
}

